src/destructors.md, src/vec-alloc.md, src/vec-dealloc.md, src/vec-deref.md, src/vec-final.md, src/vec-into-iter.md, src/vec-layout.md, src/vec-raw.md, src/vec-zsts.md
Required to land https://github.com/rust-lang/rust/pull/41064 when that's ready
=> use new Unique/heap APIs

src/destructors.md, src/vec-final.md
It'd be good to land this quickly, but please review carefully -- it's blocking a patch that makes us test src/doc in rust-lang/rust.
cc @alexcrichton
=> Update to use the new allocator APIs.

src/README.md, src/SUMMARY.md, src/meet-safe-and-unsafe.md, src/safe-unsafe-meaning.md, src/what-unsafe-does.md, src/working-with-unsafe.md
This is kinda WIP in that I haven't actually done a once-over of the changes. Interested in feedback before landing.
=> Cleanup the first chapter

src/casts.md, src/other-reprs.md, src/repr-rust.md
This decision was finalized, so now only the PRs being accepted awaits.
=> Rename C-like enums to field-less enums

src/destructors.md, src/vec-final.md
This is part of https://github.com/rust-lang/rust/pull/49669.
=> Use the new GlobalAlloc trait

src/subtyping.md
While I’m still working hard on wrapping my head around these concepts, the current definition appears non-sensical to me and my brief research on the topic. I’ve also added F to the lead to the definitions since F isn’t mentioned anywhere else.
=> Fix definition of contravariance

src/safe-unsafe-meaning.md
Updating the stale information, adding the GlobalAllocator trait.
To be honest, I'm not 100% sure there are *just* these three, but I tried grepping the standard library source code for `unsafe trait` and all the other matches seem to be still unstable.
To give a bigger context to the pull request, I feel like the nomicon would deserve some more work and love. So I'd like to start by going through it and at least updating obviously outdated information and filling in TODOs. If it's OK with everyone, I would like to be sending such pull request for a while (likely in smallish chunks, as time allows).
=> There are now 3 unsafe traits in rust

src/README.md, src/data.md, src/exotic-sizes.md, src/other-reprs.md, src/repr-rust.md
round 1, covering the first two chapters.
=> cleanups for Rust 2018

src/other-reprs.md
Broken link hunt :bow_and_arrow:
=> Fixes outdated bindgen link

src/unchecked-uninit.md
* Links to the std for some functions
* Mention the MaybeUninit
* Unify indentation (spaces, not tabs)
I was thinking about providing an example with MaybeUninit. But I'm not sure how much it is usable now, reading through the issues it seems things like `[MaybeUninit::uninit(), 50]` doesn't yet work.
Btw, I feel a bit uneasy about typing the links to the std functions, `mdbook serve` doesn't include the std for me so I can't check for them leading anywhere. Is anything checking them in CI?
=> Various unchecked-uninit improvements

src/unchecked-uninit.md
This unblocks updating upstream.
=> Fix link to copy_nonoverlapping

src/unchecked-uninit.md
Fixes https://github.com/rust-lang-nursery/nomicon/issues/150
=> update uninit section to MaybeUninit

src/safe-unsafe-meaning.md
I feel like the term "soundness" ought to come up somewhere on this page, and from what I can see the main property defined on that page is exactly that already, it's just not naming it.
r? @Centril
=> mention soundness

src/lifetimes.md
I believe a quick comment explaining how to solve the mentioned problem is suitable here.
=> Lifetimes: explain how to fix destructor example

book.toml
=> Add book.toml

src/vec-final.md
Rustup to rust-lang/rust#69609, this will unblock rust-lang/rust#69641.
=> Rustup to latest rustc

src/atomics.md
Sorry, I'm the useless-details sheriff.
=> Remove illegal space.

.github/workflows/main.yml
This can help ensure submodule updates go smoothly.
=> Use rust-lang/rust linkchecker on CI.

src/unwinding.md
=> Replace catch_panic by catch_unwind

src/vec-final.md
There was a minor API change in https://github.com/rust-lang/rust/pull/75687.
=> Fix API change to alloc::Global::grow.

src/exotic-sizes.md, src/safe-unsafe-meaning.md, src/what-unsafe-does.md
I'll probably be adding more links as I work through the book, but I thought I'd open a PR now so I don't spend time making an unwelcome change.
=> [WIP] Add more links

src/phantom-data.md
it should be covariant, right?
=> fix a typo

src/repr-rust.md
Fixes https://github.com/rust-lang/nomicon/issues/226
=> Clarify that any alignment is valid for ZSTs

src/vec-alloc.md, src/vec-dealloc.md, src/vec-drain.md, src/vec-final.md, src/vec-insert-remove.md, src/vec-into-iter.md, src/vec-layout.md, src/vec-push-pop.md, src/vec-raw.md, src/vec-zsts.md
Hi, I tried to finish the chapter about Vec. Unfortunately this chapter contains old source code that is not buildable. I had difficulties to get the code to work. Finally I found the last chapter with the actual working code.
I took this and updated the code examples. With this code it should now be possible, step by step, to evolve to the final code.
=> Update vector code examples

src/casts.md
=> Clarify casting between the same size fixed ints

src/casts.md
cc #279, closes #256
I'd suggest reviewing commit by commit.
=> Remove casting list from the nomicon

src/other-reprs.md
=> Add an example that shows the null-pointer opt does not happen

src/safe-unsafe-meaning.md
=> Clarify the Safe vs. Unsafe Rust relationship

src/unchecked-uninit.md
This is an impossible problem no longer! The example is copied straight from the stdlib.
=> Update the guidance on uninitialized data with ptr::addr_of_mut

src/borrow-splitting.md
Same as other recent PR with abbreviation
=> Clarification of borrowck

src/what-unsafe-does.md
Overflow in `unchecked_add` obviously is UB
=> specify which integer overflows we mean

src/borrow-splitting.md
This just does some cleanups of the code in the split borrows tree example, some suggested by clippy
others just seemed like simplifications that could be done.
=> Cleanups for tree example of splitting borrows

src/ffi.md
=> a typo in ffi.md
