src/SUMMARY.md
src/ffi.md

The FFI page has been copied almost verbatim from the first edition of TRPL in the master branch of [rust-lang/book](https://github.com/rust-lang/book).
I've made changes to two links that would otherwise be broken due to TRPL being a directory lower than nomicon: see 2nd commit. Unfortunately, the links will be broken in the nomicon if it's built by itself outside of [rust-lang/rust](https://github.com/rust-lang/rust).

Add FFI chapter from the first edition of TRPL to nomicon

---

src/other-reprs.md

See rust-lang/rust#27303 and rust-lang/libc#48 for discussion of the
optimization, or just try compiling `unsafe {free(malloc(16))}` with various
Rust definitions of `void *` in the FFI binding.

Document `#[repr(u8)] enum` to enable LLVM optimizations

---

src/other-reprs.md

See also the improper_ctypes lint, specifically is_repr_nullable_ptr in
src/librustc_lint/types.rs.

other-reprs: Null-pointer-optimized enums are FFI safe unless repr(C)

---

src/repr-rust.md

A line starting with `2.` unfortunately emits `<ol start="2">`, causing the bad formatting seen here:

Fixes formatting on repr(Rust) page.

---

src/subtyping.md

This matters because if `'a` were free to choose, then the argument would be trivial.  But in reality the argument also holds if `'a` was already chosen, which is what makes lifetimes special.

subtyping: clarify the concreteness of 'a in example

---

src/SUMMARY.md
src/aliasing.md
src/references.md

This replaces the mostly pointless hand-waiving model with an honest declaration of "no one knows" and a discussion of why aliasing matters.

rewrite references.md

---

src/dropck.md

This updates the compiler output in §3.9, based on `rustc 1.18.0 (03fc9d622 2017-06-06)`¹.
¹[Rust Playground](https://is.gd/uGoSfd).

Update compiler output in §3.9

---

src/other-reprs.md

The previous title suggested that `repr(isize)`, for example, was not valid.
I'm not sure if this is great wording, or whether we should add some examples, but I think we can improve the heading.

Clarify that repr(any integer type) is legal

---

src/other-reprs.md
src/safe-unsafe-meaning.md

I recently read the nomicon to delve deeper into the language. I noticed that a couple of abbreviations were never explained. These unexplained, although common abbreviations can trip a reader, as at least ABI was not immediately clear to me.

Expand first-in-book use of certain abbreviations

---

src/repr-rust.md

https://github.com/rust-lang/rust/blob/master/RELEASES.md
https://github.com/rust-lang/rust/pull/40377

Update for field reordering

---

src/dropck.md

- Fix hyperlink to RFC 1327 in the section on the dropck.
- Fix other nits

Fix RFC 1327 hyperlink in dropck

---

src/destructors.md
src/vec-final.md
src/vec-layout.md

Same as https://github.com/rust-lang-nursery/nomicon/pull/48, but into a temporary branch. Once this is merged https://github.com/rust-lang/rust/pull/46952 can update the submodule to that branch. After *that* reaches Nightly, the branch can be merged into master.

The `unique` feature is renamed `ptr_internals`

---

src/working-with-unsafe.md

`unsafe` and `mod` are not magically linked, it’s entirely up to code authors to actively use privacy to limit limit the scope of unsafety and only expose safe APIs (or `unsafe fn`s).

Clarify "unsafe pollutes the module"

---

src/working-with-unsafe.md

master has moved and the submodule in rust-lang/rust has been updated since #49, so right now https://github.com/rust-lang/rust/pull/46952 has a merge conflict. This should help solve it.

Merge 'master' into 'rust-pr-46952'

---

src/destructors.md
src/vec-final.md
src/vec-layout.md

Prior to this commit, `mdbook test` was failing

Fix code example compilation errors related to `unique`.

---

src/phantom-data.md

Replaces term 'covariance' with 'variance' to ensure consistency with other parts in the [Subtyping and Variance](https://doc.rust-lang.org/nomicon/subtyping.html) section and others.
The term 'covariance' is not used except for supplementary information for those familiar with type theory.

Replace word 'covariance' with 'variance' for consistency.

---

src/other-reprs.md

Clarify non-nullable pointer optimization in repr(C) section

---

src/destructors.md

Per https://github.com/rust-lang-nursery/nomicon/pull/62#issuecomment-380555676

Cast to `*mut _` to avoid importing std::alloc::Opaque

---

src/casts.md

https://github.com/rust-lang/rust/issues/15536 has been closed, there's no UB there, so let's stop linking to it. And for the same reasons (LLVM's assumption of the default floating point environment), f64->f32 and int->float casts do actually have a defined rounding mode, ties-to-even.

Update description of float casts

---

src/destructors.md
src/vec-final.md

This doesn't update it to be idiomatic. I think @Gankro or someone else who is
more familiar with the allocator APIs should do that; it seems like `Unique<T>`
shouldn't be used anymore (it's marked as `doc(hidden)`) but I these fixes are
sufficient for an update for rust-lang/rust.
r? @steveklabnik

Fix nomicon for allocator changes

---

.travis.yml
src/vec-final.md

Also pin mdbook version until https://github.com/rust-lang-nursery/mdBook/issues/724 is resolved

Fix for Rust changes

---

.travis.yml

Version 0.1.9 has been release and should fix `mdbook test`.

unpin mdbook version

---

src/ffi.md

Supersedes https://github.com/rust-lang-nursery/nomicon/pull/44 (which seems to have gone stale).
Fixes #29.

Don’t recommend empty enums for opaque types

---

src/destructors.md
src/vec-final.md
src/vec-layout.md

`Unique` was marked permanently-unstable in rust#46952 and its feature
flag was changed to `ptr_internals` which we're already using.
See https://github.com/rust-lang/rust/pull/46952.
Required to fix [toolstate](https://rust-lang-nursery.github.io/rust-toolstate/) as https://github.com/rust-lang/rust/pull/52644 introduced an error when an unknown feature is encountered. edit: This would also unblock nightlies.

Remove `unique` feature which doesn't exist anymore

---

src/vec-final.md

Fixed Iterator implementation for Drain
Added some tests to code
@RalfJung  - as discussed in #71 I've created separate PR for these two changes
@steveklabnik  -  in #71 you noted that test should run during `mdbook test`, but it does not seem to be so (if I modify a test to fail nothing happens) -  is there anything else needed for tests to run?

Test and fix to vec-final

---

src/SUMMARY.md
src/beneath-std.md
src/panic-handler.md
src/panic-implementation.md

r? @steveklabnik 
Required by rust-lang/rust#51366

document #[panic_handler]

---

src/borrow-splitting.md
src/checked-uninit.md
src/coercions.md
src/dropck.md
src/lifetime-mismatch.md

Fixes #89 
This changes all the compiler error messages to use the new (more readable) format.

Change compiler error message format to new format

---

src/aliasing.md

Correct small typo

---

src/exotic-sizes.md
src/other-reprs.md
src/repr-rust.md
src/what-unsafe-does.md

* We now have `union` as another composite data type
* The compiler now reorders fields and makes enums a bit smaller in
certain situations.
* We have repr(align(n)) in addition to packed.

Updates to the data layout chapter

---

src/drop-flags.md
src/phantom-data.md

Just discovered that a few source code snippets in `phantom-data.md` and `drop-flags.md` missed their syntax highlighting.

Add missing source code language hints in drop-flags and phantom-data.

---

src/subtyping.md

[Rendered](https://github.com/Gankro/nomicon/blob/subtyping2/src/subtyping.md)
This is more or less a complete rewrite of the section, as an alternative to #99

Subtyping rewrite

---

src/coercions.md

* The modern way is `dyn Trait
* Use `compile_fail` instead of ignore, to make sure it doesn't start
compiling by accident in some future version of Rust (and also to
provide link to playground).

Trivial updates to the coercions chapter

---

src/subtyping.md

This sentence could probably be slightly tweaked; the last 'it' is a little ambiguous. In any case, the fix in this patch is just a copy error.

Fix typo in subtyping.md

---

src/dropck.md

So the examples are out of date, they no longer pose a problem. However,
there's still a case where it does, so let's use that instead.
Also, mention the definition of drop order in the text, as it is
related.

dropck: The drop order is now defined

---

src/borrow-splitting.md
src/checked-uninit.md
src/phantom-data.md
src/transmutes.md

* Prefer compile_fail over ignore, to catch if the code accidentally
starts compiling in future versions.
* Make an example compile by providing mocked environment around it in
case it should be correct.
* Links into std.

Minor improvements

---

src/subtyping.md

Sorry for the trivial PR, but this read a little bit funny to me. I think that the verb should agree with the number of the subject, without consideration for the parenthetical `and especially variance`.

Fix number agreement in subtyping chapter

---

src/phantom-data.md

It seemed like "things" were missing.

Added missing "things".

---

src/vec-alloc.md

OOM behaviour in `vec-alloc.md`

---

src/lifetime-mismatch.md
src/lifetimes.md

* Updated the explanations around lifetimes a bit.
* Made sure the examples that should fail still fail in edition 2018.
* Prefer `rust,compile_fail` instead of `rust,ignore` ‒ the latter
allows the user to click on button and see the actual compile errors.
Also, this'll tell us if something stops failing.

Lifetimes: Updates to incorporate NLL

---

src/README.md

rust-lang/rust does not allow bare directory links.
This unblocks updating the submodule.

Fix some links.

---

README.md

* Re-wrap the text to fit in 80 columns.
* Suggest that people use `mdbook build --open` (similar to `cargo doc --open`) to open the book instead of having them worry about what specific OS and browser they're using.
* Make the link to the `mdbook` repo go directly to the current home of `mdbook` in the `rust-lang-nursery`  instead of relying on GitHub to redirect.

Small README.md cleanup

---

src/README.md

IMO, the link to the book shouldn't highlight the word "reading" in the [README](https://github.com/rust-lang-nursery/nomicon/blob/master/src/README.md) file.

Move word "reading" out of the link to "The Book"

---

src/lifetime-mismatch.md

When build on playground:
```
Compiling playground v0.0.1 (/playground)
warning: the item `Eq` is imported redundantly
--> src/main.rs:5:5
|
5 | use std::cmp::Eq;
|     ^^^^^^^^^^^^
|
= note: #[warn(unused_imports)] on by default
```

chore: Remove redundant Eq import

---

src/exotic-sizes.md

Added comma to `MySuperSliceable` like the other struct in `exotic-sizes`.
```
struct MySuperSlice {
info: u32,
data: [u8],
}
```
```
struct MySuperSliceable<T: ?Sized> {
info: u32,
data: T    <- probably needed in here too?
}
```

Add comma to `MySuperSliceable` too

---

src/subtyping.md

Fixes #125.
`anyway` ⇒ `any way`.

Fix typo in subtyping

---

src/what-unsafe-does.md

clarify what is UB

---

src/unchecked-uninit.md

For some reason those seem to exist in std only...?
r? @Centril

fix links for copy, copy_nonoverlapping

---

src/working-with-unsafe.md

This is basically the Nomicon side of https://github.com/rust-lang-nursery/reference/pull/647. I was not sure what the best place would be to introduce this terminology.

use sound/unsound terminology

---

src/atomics.md

Cc https://github.com/rust-lang/rust/pull/65339

atomics: C11 -> C++20

---

src/atomics.md

Thanks @petrochenkov for confirming that C++ is the origin of this model.

further clarify C11 and C/C++11 terminology

---

src/other-reprs.md

The old link returns 404, we should point to the new place.

Update unsafe-code-guidelines link

---

src/phantom-data.md

Contravariance is part of stable Rust, and it's a natural outcome of how `fn(T)` interacts with lifetimes, so it's hard to imagine this ever going away.
tl;dr: LONG LIVE CONTRAVARIANCE!

Remove mention of contravariance possibly getting scrapped

---

src/ffi.md

Make it explicit we're using `"C"` calling convention.

Fix example in FFI section Calling Rust from C

---

src/destructors.md
src/vec-final.md

Required to land https://github.com/rust-lang/rust/pull/68529. Please see that PR for details. The CI is expected to fail until the PR is landed.
EDIT: https://github.com/rust-lang/rust/pull/68529 has landed

Rename `Alloc` to `AllocRef`

---

src/subtyping.md

Added backticks around type names for consistency of document.

(minor) Add backticks around type names

---

src/send-and-sync.md

This was moved to the `negative_impls` feature in https://github.com/rust-lang/rust/pull/68004.
Fixes toolstate.

Fix negative_impls feature.

---

src/vec-alloc.md
src/vec-final.md

It's simpler (shorter) to access `MIN`/`MAX` directly on the integer types now. This repository only had a single instance of this, so the PR is tiny. But it's basically a follow up of https://github.com/rust-lang/rust/pull/69860 to make all documentation consistently use the newest versions of the constants.
r? @dtolnay

Use isize::MAX directly on type instead of module

---

src/vec-deref.md
src/vec-final.md

Accessing std this way has been stable since Rust 1.30.0.
It's shorter and simpler (and less ugly IMHO).

Use just `std::_` instead of `::std::_`

---

src/borrow-splitting.md

Update implementation code of `split_at_mut` to [latest version](https://doc.rust-lang.org/src/core/slice/mod.rs.html#1083-1093)

Update implementation code of `split_at_mut`

---

src/ffi.md

C signature in example (`void (*)(int)`) didn't match the one in the Rust code (`fn(c_int) -> c_int`). Fixed to `int (*)(int)`.

Fix example in FFI, section NPO

---

src/vec-alloc.md
src/vec-final.md
src/vec-raw.md
src/vec-zsts.md

Renamed in https://github.com/rust-lang/rust/pull/71597.  Fixes toolstate.

Rename Unique::empty to Unique::dangling

---

src/transmutes.md

The fact that the Nomicon says "Transmuting between non-repr(C) types is UB" [regularly leads to confusion](https://github.com/rust-lang/nomicon/issues/6#issuecomment-553832993), so let's fix that.

fix Nomicon transmute UB

---

src/what-unsafe-does.md

This matches https://github.com/rust-lang/reference/pull/792

Remove language-level UB for non-UTF-8 str

---

src/races.md

"one of them is a write" did not seem right to me. Doesn't generalise to the case with two concurrent threads writing to shared memory. [Related Wikipedia article](https://en.wikipedia.org/wiki/Race_condition#Example_definitions_of_data_races_in_particular_concurrency_models)

Data Race definition should be more precise

---

src/transmutes.md

* Use inline code style for `&` and `&mut`
* Add blank lines between list items to make source easier to read
* Use new-style mdBook link

Improve formatting of "Transmutes" chapter

---

src/other-reprs.md

There were two spots where it referred to `repr(rust)` when it is
usually referred to as `repr(Rust)` in accordance with `repr(C)`.
I updated those to use the uppercase form.

Uppercase `repr(Rust)`

---

src/coercions.md

As per #237 
Rendered: [coercions.md](https://github.com/mexus/nomicon/blob/master/src/coercions.md)

coercions.md: non-capturing closures to function pointers

---

src/destructors.md
src/vec-final.md

Follow-up of https://github.com/rust-lang/rust/pull/79286

Rename `AllocRef` to `Allocator` and `(de)alloc` to `(de)allocate`

---

src/vec-alloc.md

Closes #206
Fixes #229
This supersedes #206 since it mentions `malloc` but doesn't `HeapAlloc` (used on Windows).

Remove outdated information about `jemalloc`

---

src/exotic-sizes.md

This changes `https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html#tymethod.alloc` to `../std/alloc/trait.GlobalAlloc.html#tymethod.alloc` so that it uses the local docs installation if the page is viewed with the local docs, instead of https://doc.rust-lang.org.

Fix alloc link in exotic-sizes for local docs

---

src/lifetime-mismatch.md

Hello!
I wanted to see what the compiler error actually was for the given example under "Improperly reduced borrows" so I added it for future readers to see

Adds compiler error for example in Limits of Lifetimes

---

src/ffi.md

Fix for #250.
Final pattern derived by @nvzqz, with help from @dtolnay.

Fix opaque type representation.

---

src/send-and-sync.md

Add an example of thinking through whether it is sound to implement Send + Sync for a custom type that wraps a raw pointer.
I read the existing docs and was confused about whether I could implement Send + Sync for a type I wrote that wraps a c-style array. Kixiron, InfernoDeity, Talchas, and HeroicKatora on #black-magic helped me understand Send and Sync better. This example is based on the advice they gave me. I've made lots of changes, so any errors are probably mine.

Add example of thinking about Send/Sync's soundness

---

src/atomics.md

I'm not sure if this is actually desirable. For one thing, the link I used isn't
locked to c++20 exactly. But it is the same page the [std lib](https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html) links to
so that may be good for something.
I'm also not sure if other references to `C++11` should be updated or removed.
Basically, I feel like _something_ should change here but I'm not really sure what :-\

Update link to c++ atomic ordering docs

---

src/vec-alloc.md
src/vec-dealloc.md
src/vec-final.md
src/vec-insert-remove.md
src/vec-into-iter.md
src/vec-layout.md
src/vec-push-pop.md
src/vec-raw.md
src/vec-zsts.md
src/vec.md

Hi, first time contributing to the Nomicon here. I'm aware this is a somewhat large proposed change (larger than I anticipated it being when I began) but I hope it will be useful.
The chapter on implementing Vec was written to build on nightly Rust. From the discussion in 9.1 (Layout), the primary motivation for this was to get an optimized non-nullable pointer type. Since `std::ptr::NonNull` is now stable, this can achieved on stable Rust. This pull request makes the changes throughout the chapter necessary to implement Vec using `std::ptr::NonNull` instead of the unstable `Unique`.
Currently much of the code in the main body of the chapter does not compile on the latest nightly Rust because it relies on unstable APIs which have changed (for instance, `std::alloc::oom`, …

Adjust Vec to build on stable Rust

---

src/exception-safety.md
src/vec-drain.md
src/vec-final.md
src/vec-insert-remove.md
src/vec-into-iter.md
src/vec-push-pop.md
src/vec-raw.md
src/vec-zsts.md
src/working-with-unsafe.md

This a clean-up to use the [`add`](https://doc.rust-lang.org/std/primitive.pointer.html#method.add) method on raw pointers where applicable, i.e., where [`offset`](https://doc.rust-lang.org/std/primitive.pointer.html#method.offset) was being used with a cast on the index from `usize` to `isize`. This implements a [suggestion](https://github.com/rust-lang/nomicon/pull/223#discussion_r615133425) from Amanieu.

Use pointer 'add' instead of 'offset'

---

src/safe-unsafe-meaning.md

> `Send` and `Sync` are marked unsafe because thread safety is a *fundamental property* that unsafe code can't
possibly hope to defend against in the way it could defend against a buggy `Ord` implementation.
When I initially read this, I thought it was strange you'd *want* to mark `Send` and `Sync` as `unsafe` if "unsafe code can't possibly hope to defend against [thread safety]".
Here, I've attempted to clarify.

Clarify some of the language around marking traits safe/unsafe.

---

src/phantom-data.md

Add a link to show why unused lifetimes on structs are forbidden

---

src/subtyping.md

Addresses https://github.com/rust-lang/nomicon/issues/230#issuecomment-673054820. Also, marks one example `compile_fail` so that we can check the output on the book directly.

Some improvements on the "subtyping" chapter

---

book.toml
src/lifetime-mismatch.md
src/lifetimes.md

Inspired by https://github.com/rust-lang/reference/pull/1041.

Upgrade to edition 2018

---

src/aliasing.md

Clarify the conditions on the aliasing section

---

src/ffi.md

Mention "extern types" on the opaque structs section

---

src/ffi.md

The #[repr(C)] attribute on the callback example is not necessary, since the type is not used from the C code.

Removed unecessary #[repr(C)] attribute

---

book.toml
src/intro.md
theme/nomicon.css

Since we currently have a lot of outdated/missing content, it makes sense to show a warning like the reference.

Add an incomplete warning to the top page

---

src/lifetimes.md

Fix https://github.com/rust-lang/nomicon/issues/285

rename typo "lifetime" to "reference"

---

src/coercions.md

Helps #279:
- Removed the list of coercions and added a link to the reference (at a glance, the reference completely covers the items in the list here, so just removed)
- Tweaked the wording on some lines
- Updated the diagnostics

Move the list of coercions to the reference

---

src/ffi.md
src/intro.md
src/panic-handler.md

Also noted that this book uses edition 2018.

Remove unnecessary `extern crate`s

---

src/lifetime-elision.md

Currently, the lifetime elision doc only documents function definitions, but lifetime elision is also allowed in the following other locations:
* `fn` types, such as `fn(&T)`
* `Fn`/`FnMut`/`FnOnce`, such as `Fn(&T)`
* `impl` headers
To demo this up, I made some type aliases for `fn`/`Fn` which you can pass `&T` as a parameter to (to follow the lifetime rules of the surrounding context), and compared what you get with that instead of using `fn`/`Fn` directly, where lifetime elision takes on the rules from `fn`/`Fn`/etc.
I also demoed up an `impl` header that used lifetime elision twice, although the error message in that case is broken (filed https://github.com/rust-lang/rust/issues/87763)
The demo was half for this change description, and half just to make sure I understand Rust -- in …

Document lifetime elision for fn types, Fn*, impl

---

src/send-and-sync.md

Compiler even warns about unnecessary `unsafe` and unnecessary mutable variable:
- Current version [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03cc92bd31179e9de69b4630e067f7b7)
- Proposed version [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4834051727bc676eb7b3f22f661ad556)

Remove useless `unsafe`, `mut` and ptr casts in example in `send-and-sync.md`

---

src/drop-flags.md

This sentence originally confused me and it took me a while to realize that it was referring to an older Rust version rather than some edge case of drop flags in the current Rust version.
Perhaps it might be even better to name the specific Rust version where drop flags were moved out of Drop types and onto the stack. I believe that's tied to MIR, but I haven't managed to confirm about a specific Rust version in regards to the drop flags.

Clarify that drop flag fields only apply to older Rust versions

---

src/ffi.md

There's a discrepancy between the C code and the Rust code that calls it.
The Rust callback produces a return code: `fn(fn(int) -> int, int) -> int`,
but the C callback returns nothing: `void (*)(int (*)(int), int)`.

Fix typo / type error in FFI code example

---

src/ffi.md

As you may know, an empty parameter list can have [different semantics]
in C compared to a `(void)` parameter list. Also, while it's fine to
declare `main()` with an empty parameter list, it's implementation
defined as to whether it is acceptable.
Declare `main` with `(void)` so we use a standard-defined signature from
section 5.1.2.2.1 of C99.
[different semantics]: https://godbolt.org/z/fW66MsaMM

Make C code more recognizably C

---

src/other-reprs.md

This clarifies that UnsafeCell is not just repr(transparent), since it does not propagate niches the same as it's inner type, and also mentions when it can be relied on by other crates. 
For some discussion on that second point, see this issue https://github.com/rust-lang/rust/issues/90435

Clarify repr(transparent) in other-reprs

---

src/hrtb.md

Recently, [someone asked for some clarifications](https://www.reddit.com/r/rust/comments/s5yfy5/comment/ht6tq1k/?context=3) in the _easy questions_ thread on the unofficial Rust subreddit regarding the [HRTB chapter](https://doc.rust-lang.org/nomicon/hrtb.html).
They were confused by the fact that they could not simply copy&paste the _desugared_ and pseudo Rust code – with the modification `F: Fn(&'??? (u8, u16)) -> &'??? u8` → `for<'a> F: Fn(&'a (u8, u16)) -> &'a u8` applied – into the playground and have it work out of the box. 
The pseudo Rust syntax is introduced in the [lifetimes chapter](https://doc.rust-lang.org/nomicon/lifetimes.html) (basically a simplified version of `-Z unpretty=hir` with lifetime annotations in expressions) as indeed mentioned above the HRTB code example. …

Clarify the HRTB chapter

---

src/send-and-sync.md

send-and-sync: it's -> its

---

src/leaking.md

`guards` should be mutable here:
https://github.com/rust-lang/nomicon/blob/9493715a6280a1f74be759c7e1ef9999b5d13e6f/src/leaking.md#L208-L232

Fix a syntax error in leaking.md

---

src/vec/vec-alloc.md

According to the final code, `Vec::new` should be public.

Make `Vec::new` public in vec-alloc.md

---

src/transmutes.md

The current version mentions that "Transmuting an `&` to `&mut` is UB"
and then the sub-bullets (passionately!) dissuades people from doing so,
but without explaining a possible failure scenario. This change alludes
to the fact that such transmutation will run afoul of the assumptions
that the optimizer may legitimately make.

Add an explanation shared to exclusive transmute

---

src/vec/vec-drain.md
src/vec/vec-final.md
src/vec/vec-into-iter.md
src/vec/vec-raw.md

It may be better to implement [`IntoIterator`](https://doc.rust-lang.org/core/iter/trait.IntoIterator.html "The Standard Library") for `Vec`.

implement `IntoIterator` for `Vec`

---

src/vec/vec-final.md
src/vec/vec-zsts.md

This also incidentally makes the ZST code and final code have the same formatting for the divide.

Make the Vec impl be slightly more careful with ZSTs and alignment.

---

src/send-and-sync.md

Deref and DerefMut code comments both use "writers", but Deref should use "readers".

Change "writers" to "readers" for Deref.

---

src/exotic-sizes.md
src/meet-safe-and-unsafe.md
src/transmutes.md

The first occurrence of "UB" appeared without being ever introduced as an
abbreviation. It took me some time to get what it means. It was not had, but I
suspect that the space it wins in a manual is not worth its use here, so I
suggest to replace it by the two words.
However, I also suggest introduce this abbreviation explicitly, which will
prepare people who join some unsafe Rust discussion outside of this book.

"UB" vs "Undefined Behavior"

---

src/lifetimes.md

In the first change "this" and "that" is slightly ambiguous, at least for a
first introduction. Actually, I'm not 100% sure I got it right, but at least, if
I got it wrong, it proves my point it needed clarification
The second change is simply because "x has to live (for 'b to be printed)"
seemeds to mean that "'b" will be printed. I hope it makes clear that the actual
parsing is "(x has to live for 'b) in order to be printed"

Two lifetime clarification

---

src/lifetime-mismatch.md

The issue with the current version of this paragraph is that it refers to code
that will occur later. It can only be understood once we know what is borrowed
and when, which only becomes clear when the error message is shown.
With this new phrasing, I hope that the introduction prepares the reader to what
they'll find out.
Another solution would be to imitate the first example of this page. Introduce
the code with just "Given the following code:" and then comment why it
failed.

Rephrase improperly reduced borrows introduction

---

src/dropck.md
src/phantom-data.md

Dropck was never formally introduced. As it was used a single time, I just
replace it by its full length name. I also introduce it on the first "drop
checker" reference for exhaustivity.

Introduce and avoid dropck

---

src/unchecked-uninit.md

Probably obvious for most system programmer, but not for newcommers using Rust
to discover low level.

Indicate that C reference are C reference

---

src/leaking.md

I don't think "we remain", but "the section remains". Also "of it is still in
std" seems strange

Correct a sentence that didn't seem to be proper

---

src/vec/vec-push-pop.md

The way it's written, it seems to indicate that length 1 is a special case. This
should make it clear that it's just an example to illustrate the next affirmation.

State that pop for length 1 is an example

---

src/vec/vec-into-iter.md

As the event won't occur, a conditional seems more appropriate

Change will to would to discuss what don't occur

---

src/checked-uninit.md

In this case, I believe the meaning is intuitive enough that the abbreviation
makes sens. However, I still prefer to introduce it explicitly. In particular
because, in drop-flags, I misintepreted "x was uninit". I thought that "uninit"
was a verb, so that something did uninit x. It is only after some thought that I
understood that it was not a passive sentence but a descriptive one, and that
"uninit" should be understood as an adjective.

Introducing init/uninit before its use

---

src/destructors.md
src/exotic-sizes.md
src/intro.md
src/subtyping.md

Fixed some minor issues in wording/grammar.

Minor language fixes

---

src/phantom-data.md

As of [RFC 1238](https://rust-lang.github.io/rfcs/1238-nonparametric-dropck.html), these warnings have been oudated and thus a source of unnecessary fear and confusion
- ### [Rendered](https://github.com/danielhenrymantilla/nomicon/blob/patch-1/src/phantom-data.md)

Update the now stale warning about `PhantomData<T>` and dropck

---

src/ffi.md

One of the documentation changes for [RFC #2945](https://github.com/rust-lang/rfcs/blob/master/text/2945-c-unwind-abi.md).

Changes for `c_unwind`

---

src/aliasing.md

It should've said "the value of a local variable cannot alias
things...".
Fixes #362

Fix wording on the aliasing section

---

src/lifetime-mismatch.md

small fix on typo in limits of lifetimes chapter.

[typo] typo on limits of lifetime chapter

---

src/other-reprs.md

Fixes #375
Signed-off-by: Yuki Okushi <jtitor@2k36.org>

Update the `repr(transparent)` section to reflect the current state

---

src/unchecked-uninit.md

This corrects a few typos and grammatical issues in `Unchecked Uninitialized Memory` to make the text more understandable.

Fix typos and grammatical errors

---

src/lifetime-mismatch.md

"[...] stops to be needed [...]" -> "[...] ceases to be needed [...]"

Grammar change for 3.4: Limits of Lifetimes (lifetime-mismatch.md)

---

src/vec/vec-alloc.md
src/vec/vec-final.md
src/vec/vec-insert-remove.md
src/vec/vec-into-iter.md
src/vec/vec-layout.md
src/vec/vec-raw.md
src/vec/vec-zsts.md

Stop mentioning `PhantomData<T>` and dropck in the vec chapter except at the start for linking to the phantom-data chapter, and a few style improvements. See the commits for more details.

Improve chapter about `Vec<T>`

---

src/ffi.md

Creating null values of non-null types with transmute is undefined behavior, and the nomicon doesn't explicitly say that in the ["nullable pointer optimization"](https://doc.rust-lang.org/nomicon/ffi.html#the-nullable-pointer-optimization) chapter. Hopefully this comment will discourage the use of transmute in this case a little bit more.

Discourage the use of transmute to construct invalid values

---

src/borrow-splitting.md

Clippy complains with this lint on the old code: https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default

borrow-splitting: Use `take` instead of `replace`

---

src/vec/vec-raw.md

Nothing much to add, I just noticed the example code could be refactored.

vec/raw: Simplify `RawVec::grow`

---

src/dropck.md

This fixes `gatget` to say `gadget`

Fix typo in dropck documentation

---

src/ffi.md

These are minor changes that make the text flow better to me.
cc #365

Copyedits to FFI and unwinding section

---

src/send-and-sync.md

Fixes double bug in the call to libc::posix_memalign which causes SIGSEGV due to incorrect pointer parameter and EINVAL (retval=22) due to incorrect alignment when size of T is less then size of usize.

Fixes double bug in Send-Sync example

---

src/ffi.md

This sentence says "above", but the linked section is actually below.

Change incorrect reference to "above" in ffi.md

---

src/subtyping.md

The sentence refers to lifetimes being covariant, when what I believe is meant is that references are covariant over lifetimes. It might be more correct to use "references to be covariant over lifetimes," but I followed the same structure as "Box (...) to be covariant" earlier in the sentence.

Fix typo in 3.8 Subtyping and Variance

---

book.toml
src/intro.md

Is there any reason it is 2018 instead of 2021? Everything passed `mdbook test`

Update to 2021 edition

---

src/unbounded-lifetimes.md

Due to wrapping, the diff looks larger than it is. I have only changed
> The most common source of this is dereferencing a raw pointer, which produces a reference with an unbounded lifetime.
into the more accurate
> The most common source of this is taking a reference to a dereferenced raw pointer, which produces a reference with an unbounded lifetime.
See [Zulip ](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Ref.20from.20raw.20pointer.20deref.3F) discussion.
I have also expanded on the example code by expanding:
> For instance:
> ```rust,ignore
> fn get_str<'a>() -> &'a str;
> ```
> will produce an `&str` with an unbounded lifetime.
into:
> For instance:
> 
> ```rust
> fn get_str<'a>(s: *const String) -> &'a str {
>     unsafe { &*s }
> }
> 
> fn main() {
>     let …
```

Expand unbounded lifetime example code and improve wording

---

src/subtyping.md

This is to address the issues raised in #339

Rewrite the chapter on subtyping and variance

---

src/phantom-data.md

phantom-data: Add `Send` and `Sync` columns

---

src/ffi.md

Tracking issue: rust-lang/rust#42202
This is blocked on the stabilization of `thiscall_abi`.

Document thiscall abi

---

src/what-unsafe-does.md

This would need a bunch of caveats: when data is pinned, it *is* unsound to not call the destructors (pinning wasn't a thing yet when the nomicon got written); also code can rely on the destructors in its own stack frame to be executed if the stack frame ever gets popped (i.e., longjmp-ing over the stack frame is not okay).

remove 'fail to call destructors' from okay-list

---

src/beneath-std.md

[Rendered](https://github.com/kadiwa4/nomicon/blob/beneath_std/src/beneath-std.md)
Based on [this page](https://doc.rust-lang.org/nightly/unstable-book/language-features/lang-items.html) in the Unstable Book. I want to update it (see rust-lang/rust#110274) and I think a lot of information doesn't belong there and is better kept here. The examples can even be tested.
If people don't think that this page fits here, another option would be to create a page for rustc's `start` feature flag (in the Unstable Book) and put the information there.

Fill "Beneath `std`"

---

src/exception-safety.md

Fixed `Hole::get` marked as unsafe in `exception-safety.md`

---

src/races.md

The section on preventing general race conditions is a bit hand wavy. Change wording to be more concrete, and add an example of Rust preventing general races in a very specific case.

Reword the section on general race conditions

---

src/phantom-data.md

- simplify and clarify the auto-traits (_c.f._, #411)
- No more `-` in the auto-traits part
- move `dropck` to its own dedicated column
- Name the `'a` and `T` columns with "variance"
- Emphasize the `cov` _vs._ `inv` _vs._ `contra` distinctions
- Add a mention to the `PhantomPinned` type.
___
- [Rendered](https://github.com/danielhenrymantilla/nomicon/blob/phantomdata-table/src/phantom-data.md)
- Preview of the diff (as of the first commit):

Improve the `PhantomData` table

---

src/vec/vec-drain.md
src/vec/vec-final.md
src/vec/vec-insert-remove.md
src/vec/vec-into-iter.md
src/vec/vec-layout.md
src/vec/vec-raw.md

- Make both comparisons that call `grow()` use the same order of `len` and `cap`
- Use shorthand notation for field initialization, just as its being used across the book's codebase
- Remove unused import (PhantomData) in the Layout page
- Limit scope of `unsafe` usage to only where it's really needed
I copied the "Final Code" page into a local `cargo new --lib` folder and it compiled and ran tests successfully :heavy_check_mark: (edit: I forgot the CI is running doc tests lol)

Minor improvements to Vec

---

src/subtyping.md

Relates to the libs update at https://github.com/rust-lang/rust/pull/119534

Update an example of `thread_local` to use `local_key_cell_methods`

---

src/beneath-std.md

I've run into this because my other PR breaks these examples: https://github.com/rust-lang/rust/pull/124050
(also the comment about `crt0.o` on these can't be right, because this was being built on Windows)

Tidy up beneath-std, support Windows-MSVC without libc

---

src/other-reprs.md

The text makes it sound like only the size matters, but `i32` and `u32` are not ABI-compatible so we have to talk about size and sign here.

repr(int) enums: both size and sign matter

---

src/exotic-sizes.md

This is a documentation change to accompany [this stabilization report](https://github.com/rust-lang/rust/pull/122792). It should only be merged if the stabilization gets accepted.

Stabilize `min_exhaustive_patterns`

---

.github/workflows/main.yml

This switches PRs to use merge queues to help ensure that master is evergreen.

CI: Switch to merge queue

---

src/races.md

One might carelessly misread a sentence that begins “data races are *mostly* prevented” as suggesting that Rust fails to prevent some data races.  Clarify the intended reading.

races: Clarify a “mostly” that might be misread

---

src/races.md

The first example shows that you "can't violate memory safety with safe Rust" and the second example shows that you "can violate memory safety with unsafe Rust".
The second example does not demonstrate a data race since there is only one thread touching `data`.
Fixes #466

races.md: data race -> race condition to violate memory safety

---

src/arc-mutex/arc-drop.md

"Mutex\<T\>" in markdown is interpreted as "Mutex" followed by an inline HTML tag `<T>` and therefore rendered as "Mutex" without the "\<T\>" ([playground](https://spec.commonmark.org/dingus/?text=%3E%20In%20particular%2C%20while%20the%20contents%20of%20an%20Arc%20are%20usually%20immutable%2C%20it%27s%0A%3E%20possible%20to%20have%20interior%20writes%20to%20something%20like%20a%20Mutex%3CT%3E.%20Since%20a%20Mutex%0A%3E%20is%20not%20acquired%20when%20it%20is%20deleted%2C%20we%20can%27t%20rely%20on%20its%20synchronization%20logic%0A%3E%20to%20make%20writes%20in%20thread%20A%20visible%20to%20a%20destructor%20running%20in%20thread%20B.%0A)).

Fix accidental inline HTML in Markdown

---

src/unchecked-uninit.md

The doc page on [addr_of_mut](https://doc.rust-lang.org/std/ptr/macro.addr_of_mut.html) and [addr_of](https://doc.rust-lang.org/std/ptr/macro.addr_of.html) state that the macros are soft deprecated in favor of &raw mut/&raw const.

Update guidance on uninitialized fields to use &raw mut instead of addr_of_mut!

---

src/beneath-std.md

The `#![start]` attribute has been removed in
https://github.com/rust-lang/rust/pull/134299.

Remove `#![start]` attribute

---

src/ffi.md

There once was [a comment](https://github.com/rust-lang/nomicon/commit/90811705ca28c1e2a7e85315a154c464c0f42c5b#diff-ed2118bc56f30badbb9126d150cd476a09dafe0e1f9a4f310b6c86da2589b4b0L757-L758) in the opaque structs section of the FFI chapter which explained that the empty array is used to avoid a warning around  `()` in FFI. Since Rust 1.72, the compiler [no longer warns](https://github.com/rust-lang/rust/pull/113457/commits/24f90fdd2654e9c5437a684d3a72a4e70826a985) about using `()` in FFI.
This PR swaps `[u8; 0]` for `()` in the example opaque structs to avoid any future confusion.

Use `()` instead of `[u8; 0]` in opaque type

---

src/other-reprs.md

Expand the `repr(packed)` section to note if also supports an explicit power-of-two argument like `repr(align(n))`.

other-reprs: Add details for n!=1 repr(packed)

---

src/exotic-sizes.md

* "because" is not that good at the start of a sentence
* "although" should be followed by two sub-sentences

Improve grammar in exotic-sizes

---

src/other-reprs.md

Until something like https://github.com/rust-lang/rust/pull/128600 lands, let's be careful what we say about this.
Also mention that `repr(C)` generally makes this behave the same as C ABI-wise. That's anyway what people already assume this means and are relying on in practice, so there's no point in not saying it IMO?
Cc @rust-lang/opsem @chorman0773

other-reprs: do not make it sound like we are making ABI promises for repr(int) enums

---

.github/workflows/main.yml
book.toml
src/beneath-std.md
src/ffi.md
src/intro.md
src/other-reprs.md
src/send-and-sync.md

I noticed this was still using Rust 2021, so I went and updated it for the 2024 edition.

Update to 2024 edition

---

src/ffi.md

The rust-intrinsic ABI has been removed from the compiler in rust-lang/rust#139455 as part of rust-lang/rust#132735

remove `rust-intrinsic` ABI

---

src/ffi.md

Fixes up some word soup I came across reading the chapter.

Remove double wording in opaque type chapter

---

src/exotic-sizes.md

The new rules were tracked in
https://github.com/rust-lang/rust/issues/117945
The corresponding update to the Reference was
https://github.com/rust-lang/reference/pull/1541
See also #198

Say that dereferencing a pointer to a ZST is no longer undefined

---

src/unchecked-uninit.md

Inline const expressions were stabilized in Rust 1.79. They allow us to avoid the unsafe call to MaybeUninit::assume_init() and its explanation.
https://blog.rust-lang.org/2024/06/13/Rust-1.79.0/#inline-const-expressions

Use inline const expression in unchecked-uninit.md

---

src/vec/vec-zsts.md

Fix https://github.com/rust-lang/nomicon/issues/424

Handle drop zst

---

src/ffi.md

In the "[Calling foreign functions](https://doc.rust-lang.org/nomicon/ffi.html#calling-foreign-functions)" section of the FFI chapter, an example `extern` block is given that reads like so:
```
#[link(name = "snappy")]
unsafe extern "C" {
fn snappy_max_compressed_length(source_length: size_t) -> size_t;
}
```
This example is then expanded upon later in the section, with the following code:
```
#[link(name = "snappy")]
unsafe extern {
fn snappy_compress(input: *const u8,
input_length: size_t,
compressed: *mut u8,
compressed_length: *mut size_t) -> c_int;
fn snappy_uncompress(compressed: *const u8,
compressed_length: size_t,
uncompressed: *mut u8,
uncompressed_length: *mut size_t) -> c_int;
fn snappy_max_compressed_length(source_length: size_t) -> size_t;
fn …
```

Add missing "C" ABI to FFI example code
